# Builder image
FROM debian:bookworm as builder

# Install Squid
RUN apt-get update && apt-get install -y squid-openssl && apt-get clean

RUN openssl genrsa 2048 > /etc/squid/ca_key.pem
RUN openssl req -new -x509 -nodes -days 365000 -subj "/C=GB/O=Clotho Proxy/CN=example.com" -key /etc/squid/ca_key.pem -out /etc/squid/ca_cert.pem

# RUN chmod 400 /etc/squid/ca_key.pem
# RUN chown squid:squid /etc/squid/ca_key.pem
RUN mkdir -p /var/lib/squid
RUN /usr/lib/squid/security_file_certgen -c -s /var/lib/squid/ssl_d -M 12MB

# Copy your icapd binary into the builder image

COPY config.yaml /usr/local/bin/config.yaml
COPY squid.conf /etc/squid/squid.conf
COPY icapd /usr/local/bin/icapd
COPY start.sh /start.sh

RUN chmod +x /start.sh

ENTRYPOINT ["./start.sh"]

EXPOSE 3128 3128

